# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test parser

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Deps
      run: |
        python -m pip install coverage==7.6.10 pylint==3.3.3
        coverage --version
    - name: Lint
      run: |
        pylint ttv_parser
    - name: Test
      run: |
        coverage run -m test.parser_test
    - name: Coverage
      run: |
        coverage report -m
